//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroRequest
    {
        public int ID { get; set; }
        public Nullable<int> Sender_ID { get; set; }
        public Nullable<int> Receiver_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> User_ID1 { get; set; }
        public string Message { get; set; }
    }
}
