//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataSchema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bromanceEntities : DbContext
    {
        public bromanceEntities()
            : base("name=bromanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<BroRequest> BroRequests { get; set; }
        public DbSet<Circle> Circles { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<Hobby> Hobbies { get; set; }
        public DbSet<Liking> Likings { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<TextPost> TextPosts { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
