//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int ID { get; set; }
        public Nullable<int> Album_ID { get; set; }
        public string Caption { get; set; }
    }
}
