//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroRequest
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserId { get; set; }
        public int UserId1 { get; set; }
    
        public virtual RequestNotification RequestNotification { get; set; }
        public virtual User Sender { get; set; }
        public virtual User Receiver { get; set; }

        public bool Accept()
        {
            bool successful = false;

            successful = Sender.GetCircleByName("Bros").AddBro(Receiver);
            successful = Receiver.GetCircleByName("Bros").AddBro(Sender);

            return successful;
        }

        public void Dismiss()
        {
            this.RequestNotification.IsRead = true;
        }
    }
}
