//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle
    {
        public Circle()
        {
            this.Members = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<User> Members { get; set; }
        public virtual User Owner { get; set; }

        public void AddBro(User bro)
        {
            Members.Add(bro);
        }
    }
}
