//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle
    {
        public Circle(string Name, User Owner)
        {
            this.Members = new HashSet<User>();
            this.Name = Name;
            this.Owner = Owner;
        }

        public bool AddBro(User Bro){
            bool BroValid = ValidateBro(Bro);

            if (BroValid)
            {
                Members.Add(Bro);
            }

            return BroValid;
        }

        public bool ValidateBro(User Bro)
        {
            bool broValid = true;

            broValid = !Members.Contains(Bro);

            return broValid;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Members { get; set; }
        public virtual User Owner { get; set; }
    }
}
