//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstBump : Notification
    {
        public FirstBump()
        {
            this.Sender = new HashSet<User>();
        }
    
    
        public virtual ICollection<User> Sender { get; set; }
    }
}
