//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Albums = new HashSet<Album>();
            this.Posts = new HashSet<Post>();
            this.Comments = new HashSet<Comment>();
            this.SentBroRequests = new HashSet<BroRequest>();
            this.ReceivedBroRequests = new HashSet<BroRequest>();
            this.JoinedCircles = new HashSet<Circle>();
            this.OwnedCircles = new HashSet<Circle>();
            this.MessagesSent = new HashSet<Message>();
            this.MessagesReceived = new HashSet<Message>();
            this.Notifications = new HashSet<Notification>();
            this.Preferences = new HashSet<Preference>();
            this.BlockedBros = new HashSet<User>();
            this.BlockedByBros = new HashSet<User>();
        }

        public void CreateCircle(string CircleName)
        {
            OwnedCircles.Add(new Circle(CircleName, this));
        }

        public void AddBroToCircle(User Bro, Circle targetCircle)
        {
            targetCircle.AddBro(Bro);
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public byte[] Salt { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<BroRequest> SentBroRequests { get; set; }
        public virtual ICollection<BroRequest> ReceivedBroRequests { get; set; }
        public virtual ICollection<Circle> JoinedCircles { get; set; }
        public virtual ICollection<Circle> OwnedCircles { get; set; }
        public virtual ICollection<Message> MessagesSent { get; set; }
        public virtual ICollection<Message> MessagesReceived { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual Profile Profiles { get; set; }
        public virtual ICollection<User> BlockedBros { get; set; }
        public virtual ICollection<User> BlockedByBros { get; set; }
        public virtual FirstBump SentFirstBumps { get; set; }
    }
}
