//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bros.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class User
    {
        public User()
        {
            this.JoinedCircles = new HashSet<Circle>();
            this.BlockedBros = new HashSet<User>();
            this.BlockedByBros = new HashSet<User>();
            this.Posts = new HashSet<Post>();
            this.SentMessages = new HashSet<Message>();
            this.ReceivedMessages = new HashSet<Message>();
            this.Circles = new HashSet<Circle>();
            this.Albums = new HashSet<Album>();
            this.Preferences = new HashSet<Preference>();
            this.SentBroRequests = new HashSet<BroRequest>();
            this.ReceivedBroRequests = new HashSet<BroRequest>();
            this.SentFirstBumps = new HashSet<FirstBump>();
            this.Notifications = new HashSet<Notification>();
            this.Comments = new HashSet<Comment>();

            if (this.GetCircleByName("Bros") == null)
            {
                this.CreateCircle("Bros");
            }
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Email { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsBanned { get; set; }
    
        public virtual ICollection<Circle> JoinedCircles { get; set; }
        public virtual ICollection<User> BlockedBros { get; set; }
        public virtual ICollection<User> BlockedByBros { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Message> SentMessages { get; set; }
        public virtual ICollection<Message> ReceivedMessages { get; set; }
        public virtual ICollection<Circle> Circles { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<BroRequest> SentBroRequests { get; set; }
        public virtual ICollection<BroRequest> ReceivedBroRequests { get; set; }
        public virtual ICollection<FirstBump> SentFirstBumps { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }

        public void SendBroRequest(User bro)
        {
            using (ModelFirstContainer context = new ModelFirstContainer())
            {
                BroRequest request = new BroRequest();
                request.SetUsers(this, bro);

                this.SentBroRequests.Add(request);
                this.Notifications.Add(request.RequestNotification);

                bro.ReceivedBroRequests.Add(request);
                bro.Notifications.Add(request.RequestNotification);

                context.SaveChanges();
            }
        }

        public void AddBroToCircle(User Bro, Circle targetCircle)
        {
            targetCircle.AddBro(Bro);
        }

        public Circle GetCircleByName(string CircleName)
          {
              return Circles.Where(c => c.Name == CircleName).FirstOrDefault();
          }

        public void CreateCircle(string CircleName)
        {
            Circle targetCircle = new Circle();
            targetCircle.Name = CircleName;
            targetCircle.Owner = this;
            Circles.Add(targetCircle);
        }
    }
}
