// <auto-generated />
namespace Bros.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tir));
        
        string IMigrationMetadata.Id
        {
            get { return "201311200802344_tir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
