// <auto-generated />
namespace Bros.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class enable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enable));
        
        string IMigrationMetadata.Id
        {
            get { return "201311202200034_enable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
